//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supremacy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Supremacy.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array has non-zero lower bound..
        /// </summary>
        internal static string ArgumentException_ArrayHasNonZeroLowerBound {
            get {
                return ResourceManager.GetString("ArgumentException_ArrayHasNonZeroLowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array must be single-dimensional..
        /// </summary>
        internal static string ArgumentException_ArrayMustBeSingleDimensional {
            get {
                return ResourceManager.GetString("ArgumentException_ArrayMustBeSingleDimensional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array type is incompatible with the collection type..
        /// </summary>
        internal static string ArgumentException_ArrayTypeIncompatibleWithCollectionType {
            get {
                return ResourceManager.GetString("ArgumentException_ArrayTypeIncompatibleWithCollectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad comparand type..
        /// </summary>
        internal static string ArgumentException_BadComparandType {
            get {
                return ResourceManager.GetString("ArgumentException_BadComparandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All elements in &apos;{0}&apos; must be of the exact type &apos;{1}&apos;..
        /// </summary>
        internal static string ArgumentException_ElementExactTypeMismatch {
            get {
                return ResourceManager.GetString("ArgumentException_ElementExactTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All elements in &apos;{0}&apos; must derive from type &apos;{1}&apos;..
        /// </summary>
        internal static string ArgumentException_ElementTypeMismatch {
            get {
                return ResourceManager.GetString("ArgumentException_ElementTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be of type {0}..
        /// </summary>
        internal static string ArgumentException_IncorrectType {
            get {
                return ResourceManager.GetString("ArgumentException_IncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter must be an enum type..
        /// </summary>
        internal static string ArgumentException_ParameterMustBeEnumType {
            get {
                return ResourceManager.GetString("ArgumentException_ParameterMustBeEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not defined for enum type &apos;{0}&apos;..
        /// </summary>
        internal static string ArgumentException_UndefinedEnumValueFormat {
            get {
                return ResourceManager.GetString("ArgumentException_UndefinedEnumValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a non-null, non-empty string..
        /// </summary>
        internal static string ArgumentException_ValueMustBeNonEmptyString {
            get {
                return ResourceManager.GetString("ArgumentException_ValueMustBeNonEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is outside the bounds of the array..
        /// </summary>
        internal static string ArgumentOutOfRangeException_IndexIsOutsideArrayBounds {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_IndexIsOutsideArrayBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start index plus item count is greater than the length of the array..
        /// </summary>
        internal static string ArgumentOutOfRangeException_StartPlusCountExceedsLength {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_StartPlusCountExceedsLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be non-negative..
        /// </summary>
        internal static string ArgumentOutOfRangeException_ValueMustBeNonNegative {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_ValueMustBeNonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation cannot be performed after initialization has completed..
        /// </summary>
        internal static string InvalidOperationException_AlreadyInitialized {
            get {
                return ResourceManager.GetString("InvalidOperationException_AlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection was of a fixed size..
        /// </summary>
        internal static string NotSupported_FixedSizeCollection {
            get {
                return ResourceManager.GetString("NotSupported_FixedSizeCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection is read only..
        /// </summary>
        internal static string NotSupported_ReadOnlyCollection {
            get {
                return ResourceManager.GetString("NotSupported_ReadOnlyCollection", resourceCulture);
            }
        }
    }
}
